### ISSUE TITLE
sample code contains self

### ISSUE THREAD

**Issue by hannesdelbeke** [MaxRocamora/QtLog#1]
this wont work since you try use self outside a class.
```
# create the log widget
    self.loggers = QtUILogger(parent=self, layout_widget=self.ui.log_layout, loggers=[log, log_ext])
```

another thign that can be improved: 
requiring layout_widget is bad practice for widgets. since now i can't make one without

**Comment by MaxRocamora** [comment]
Hi, I should update the readme for clarity, the log must be used inside your qt application, and linked to a layout, where it will be displayed.
The QtLog is a QPlainTextEdit widget, and ask for layout to be added. I leave the layout widget creation to the user.
See the example/main.py file for a complete example.
